### ISSUE TITLE
flux-sched v0.7.1 release

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched-v0.7#5]
What is required to finalize a v0.7.1 release? We'll want to get this done by next week if possible, so RPMs can be built to make it into the next TOSS release (end of month).

Besides release notes, anything left to do here?

**Comment by dongahn** [comment]
I don't have anything else on my plate. Just needed AMD GPU support for CORONA. If someone can run  some actual AMD GPU based test codes with this and latest core this would be a big plus though.

**Comment by grondo** [comment]
Supposedly we can get early access to Corona at this point. I don't have any test code to try out but I think @SteVwonder was looking into this. Shall I propose a PR to add NEWS entry for 0.7.1?

**Comment by dongahn** [comment]
> Shall I propose a PR to add NEWS entry for 0.7.1?

Yes. Thank you @grondo!

**Comment by SteVwonder** [comment]
> Supposedly we can get early access to Corona at this point.

I did get access to Corona.  :fireworks: 

> If someone can run some actual AMD GPU based test codes with this and latest core this would be a big plus though.

At minimum, I can run something like [opencl-info](https://github.com/marchv/opencl-info) under Flux.  I'm having trouble getting it to work interactively though.  When building against `/opt/rocm/opencl`, the output when running `opencl-info` is: `ERROR: clGetPlatformIDs(-1001)`.  @dongahn or @trws: have either of you compiled and run an OpenCL app on Corona yet?  Or have any suggestions for a better GPU app to build/run?

**Comment by dongahn** [comment]
@SteVwonder: I will look for some tomorrow. I think using simple OMP4 and HIP codes will give us good coverage. We probably don't need an opencl case.

**Comment by grondo** [comment]
@dongahn, @SteVwonder  we should get v0.7.1 tagged by this week to make it into next TOSS release. Are we waiting for anything and how can I help?

**Comment by dongahn** [comment]
I was hoping to see some actual AMD GPU code testing on CORONA. But maybe what @SteVwonder did can be considered as a smoke test which seem okay. I won’t have time to do this anytime soon because of other priorities. So I would say, we tag as is and leave more testing for a later time.

Dong

**Comment by grondo** [comment]
Ok, I pushed [v0.7.1](https://github.com/flux-framework/flux-sched-v0.7/releases/tag/v0.7.1)

**Comment by dongahn** [comment]
Thanks @grondo!

**Comment by grondo** [comment]
Unfortunately Koji is down right now so we won't be able to build packages just yet...

**Comment by SteVwonder** [comment]
> I was hoping to see some actual AMD GPU code testing on CORONA.  So I would say, we tag as is and leave more testing for a later time.

This bubbled up to the top of my TODO list.  I think if we get https://github.com/flux-framework/flux-core-v0.11/issues/20 handled, this will work correctly.

**Comment by dongahn** [comment]
Ok thanks. BTW getting this to work on chimera would be a stretch because of the GPU numbering scheme and such for muti.GPU types is not defined clearly at all. I would recommend Corona or Crayz instead.
